/**
 * BetaValueDeconvolution.java
 *
 * Per-region beta-value tissue-of-origin deconvolution using quadratic programming.
 * Reimplements the original FinaleMe paper's approach in Java:
 *   1. Tile CGI+shore regions into 1kb non-overlapping windows
 *   2. Collapse per-CpG methylation to per-window methylation density
 *   3. Filter windows by coverage and variability
 *   4. Binarize methylation levels
 *   5. Solve constrained optimization: minimize ||Y - X*w||^2
 *      subject to sum(w)=1, w>=0
 *
 * Avoids UXM haplotype-based deconvolution issues (X-inflation) by operating
 * on per-CpG beta values rather than per-read methylation patterns.
 *
 * @author yaping (lyping1986@gmail.com)
 */
package edu.northwestern.epifluidlab.finaleme.utils;

import org.apache.commons.math3.linear.*;
import org.kohsuke.args4j.Argument;
import org.kohsuke.args4j.CmdLineException;
import org.kohsuke.args4j.CmdLineParser;
import org.kohsuke.args4j.Option;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;
import java.util.zip.GZIPInputStream;

public class BetaValueDeconvolution {

    private static final Logger log = LoggerFactory.getLogger(BetaValueDeconvolution.class);

    // ========================= CLI Options =========================

    @Option(name = "-markerRegions", usage = "Pre-defined marker regions file (atlas TSV or BED with startCpG/endCpG). "
            + "Uses these regions instead of tiling CGI+shore into windows. "
            + "Skips window generation and variability filtering. "
            + "If the file contains embedded per-cell-type values (e.g., count ratios), "
            + "it can be used directly without -refBetas/-refGroups.")
    public String markerRegionsFile = null;

    @Option(name = "-cgiShoreRegions", usage = "CGI+shore BED file (chr, start, end). Required unless -markerRegions is used.")
    public String cgiShoreBed;

    @Option(name = "-refPanel", usage = "Pre-aggregated reference panel TSV (chrom, start, end, CellType1, ...). "
            + "Each cell value is either a float beta (0.85) or methylated_count/total_count (125/250). "
            + "Generated by generate_cgi_shore_markers.py stage 4. "
            + "When set, -refBetas and -refGroups are not needed (the panel already contains the aggregated per-cell-type values).")
    public String refPanelFile = null;

    @Option(name = "-refBetas", usage = "Comma-separated reference .beta files, or a .txt file listing one path per line")
    public String refBetasArg;

    @Option(name = "-refGroups", usage = "CSV file mapping sample names to cell types (columns: name, group)")
    public String refGroupsFile;

    @Option(name = "-cpgIndex", usage = "CpG index BED file (e.g., data/CpG_index.hg19.bed.gz)")
    public String cpgIndexFile;

    @Option(name = "-windowSize", usage = "Window size in bp for tiling (default: 1000)")
    public int windowSize = 1000;

    @Option(name = "-minCoverage", usage = "Minimum total Cs+Ts per window across all references (default: 10)")
    public int minCoverage = 10;

    @Option(name = "-topVariablePercent", usage = "Fraction of most variable windows to keep (default: 0.01 = top 1%)")
    public double topVariablePercent = 0.01;

    @Option(name = "-binarizeThreshold", usage = "Methylation density threshold for binarization (default: 0.1)")
    public double binarizeThreshold = 0.1;

    @Option(name = "-solver", usage = "Solver method: NNLS (Lawson-Hanson + normalize, default) or QP (Goldfarb-Idnani)")
    public String solver = "NNLS";

    @Option(name = "-replicateMode", usage = "How to combine replicates: aggregate (sum counts, default) or average (mean of ratios)")
    public String replicateMode = "aggregate";

    @Option(name = "-output", usage = "Output TSV file (default: stdout)")
    public String outputFile = null;

    // ========================= Bootstrap / Inference Options =========================

    @Option(name = "-bootstrap", usage = "Enable bootstrap: resample markers with replacement B times, re-run NNLS "
            + "per replicate, produce CI, p-value (for H0: w_k = 0), and BH-adjusted q-value per cell type. "
            + "When enabled the output format switches from wide (one column per sample) to long with "
            + "additional columns (CI_lower, CI_upper, p_value, q_value). Default: false")
    public boolean bootstrap = false;

    @Option(name = "-nBootstrap", usage = "Bootstrap replicates (default: 200). Recommended >=200 for stable CIs "
            + "and >=1000 for stable small p-values.")
    public int nBootstrap = 200;

    @Option(name = "-ciLevel", usage = "Two-sided CI level for bootstrap (default: 0.95 -> percentile CI [2.5, 97.5])")
    public double ciLevel = 0.95;

    @Option(name = "-bootstrapThreads", usage = "Parallelism for bootstrap replicates (default: 1). "
            + "Each replicate runs NNLS independently; bootstrap is embarrassingly parallel.")
    public int bootstrapThreads = 1;

    @Option(name = "-bootstrapSeed", usage = "RNG seed for bootstrap resampling for reproducibility (default: -1, "
            + "meaning use fresh entropy). Set to a non-negative integer to fix the resampling order.")
    public long bootstrapSeed = -1L;

    @Option(name = "-fdrAlpha", usage = "FDR threshold for the 'significant' flag in the per-cell-type output "
            + "(q_value <= fdrAlpha -> significant=YES). Default: 0.05")
    public double fdrAlpha = 0.05;

    @Option(name = "-bootstrapStratified", usage = "Stratified bootstrap: resample markers WITHIN each cell-type "
            + "group (from the `target` column in the reference panel) rather than uniformly across all markers. "
            + "Eliminates the inflated-variance bias for cell types with fewer markers. Falls back to uniform "
            + "resampling if the reference panel has no `target` column. Default: false")
    public boolean bootstrapStratified = false;

    @Option(name = "-permutationTest", usage = "Column-permutation test: for each cell type c, shuffle the rows of "
            + "the c-th reference column, re-run NNLS, and compute p_c = (k+1)/(B+1) where k = #{permuted w_c >= "
            + "observed w_c}. Produces frequentist-calibrated p-values that can resolve below 1/(bootstrap B+1). "
            + "BH-adjusted to q-values across cell types. When enabled, replaces the bootstrap-tail p in the "
            + "output; bootstrap is still run (if enabled) for the CI. Default: false")
    public boolean permutationTest = false;

    @Option(name = "-nPermutations", usage = "Number of column permutations per cell type (default: 1000). Each "
            + "cell type gets its own independent set of permutations, so total NNLS solves = K * nPermutations. "
            + "Recommended: 1000 for routine use, 10000 when you want to resolve small p-values.")
    public int nPermutations = 1000;

    @Option(name = "-permutationSeed", usage = "RNG seed for permutation tests (default: -1 = fresh entropy). "
            + "Set to a non-negative integer to fix the permutation order.")
    public long permutationSeed = -1L;

    @Option(name = "-h", usage = "Show help")
    public boolean help = false;

    @Argument
    private List<String> queryFiles = new ArrayList<>();

    private static final String USAGE =
            "BetaValueDeconvolution [opts] "
                    + "{-refPanel <TSV> | (-markerRegions with embedded values) | -refBetas <betas> -refGroups <CSV>} "
                    + "{-markerRegions <TSV/BED> | -cgiShoreRegions <BED>} "
                    + "sample1.beta [sample2.prediction.bed.gz ...]";

    // ========================= Data Structures =========================

    static class Window {
        String chr;
        int start, end;
        int startCpgIdx, endCpgIdx; // 1-based global CpG indices

        Window(String chr, int start, int end, int startCpgIdx, int endCpgIdx) {
            this.chr = chr;
            this.start = start;
            this.end = end;
            this.startCpgIdx = startCpgIdx;
            this.endCpgIdx = endCpgIdx;
        }

        String id() {
            return chr + ":" + start + "-" + end;
        }
    }

    static class CpgIndex {
        final LinkedHashMap<String, int[]> chrPositions;
        final HashMap<String, Integer> chrOffsets;
        final int totalSites;

        CpgIndex(LinkedHashMap<String, int[]> chrPositions,
                 HashMap<String, Integer> chrOffsets, int totalSites) {
            this.chrPositions = chrPositions;
            this.chrOffsets = chrOffsets;
            this.totalSites = totalSites;
        }

        /** Find the 1-based global CpG index for the first CpG at or after genomic position. */
        int getFirstCpgIndexAtOrAfter(String chr, int pos) {
            int[] positions = chrPositions.get(chr);
            Integer offset = chrOffsets.get(chr);
            if (positions == null || offset == null) return -1;
            int idx = Arrays.binarySearch(positions, pos);
            if (idx < 0) idx = -(idx + 1); // insertion point
            if (idx >= positions.length) return -1;
            return offset + idx + 1; // 1-based
        }

        /** Find the 1-based global CpG index for the last CpG before genomic position. */
        int getLastCpgIndexBefore(String chr, int pos) {
            int[] positions = chrPositions.get(chr);
            Integer offset = chrOffsets.get(chr);
            if (positions == null || offset == null) return -1;
            int idx = Arrays.binarySearch(positions, pos);
            if (idx < 0) idx = -(idx + 1) - 1; // element before insertion point
            if (idx < 0) return -1;
            return offset + idx + 1; // 1-based
        }
    }

    static class WindowCpgLookup {
        final int[] startsInclusive; // 1-based global CpG index
        final int[] endsExclusive;   // 1-based global CpG index
        final int[] windowIndices;   // index into selected windows

        WindowCpgLookup(List<int[]> entries) {
            // entries: [startCpgInclusive, endCpgExclusive, windowIndex]
            entries.sort(Comparator.comparingInt(a -> a[0]));
            startsInclusive = new int[entries.size()];
            endsExclusive = new int[entries.size()];
            windowIndices = new int[entries.size()];
            for (int i = 0; i < entries.size(); i++) {
                int[] e = entries.get(i);
                startsInclusive[i] = e[0];
                endsExclusive[i] = e[1];
                windowIndices[i] = e[2];
            }
        }

        int findWindowIndex(int globalCpgIdx) {
            // Rightmost interval start <= globalCpgIdx
            int lo = 0, hi = startsInclusive.length - 1;
            int pos = -1;
            while (lo <= hi) {
                int mid = (lo + hi) >>> 1;
                if (startsInclusive[mid] <= globalCpgIdx) {
                    pos = mid;
                    lo = mid + 1;
                } else {
                    hi = mid - 1;
                }
            }
            if (pos < 0) return -1;
            return globalCpgIdx < endsExclusive[pos] ? windowIndices[pos] : -1;
        }
    }

    // ========================= Main =========================

    /**
     * Per-marker primary cell-type label (the `target` column in the reference
     * panel TSV). Populated by {@link #loadReferencePanel} and consumed by
     * stratified bootstrap. Null / empty when the panel has no `target` column
     * (in which case bootstrap falls back to uniform resampling).
     * Aligned 1-to-1 with the rows of {@code refSelected} (post-binarization).
     */
    private List<String> markerTargets = new ArrayList<>();

    public static void main(String[] args) throws Exception {
        new BetaValueDeconvolution().doMain(args);
    }

    public void doMain(String[] args) throws Exception {
        CmdLineParser parser = new CmdLineParser(this);
        try {
            parser.parseArgument(args);
        } catch (CmdLineException e) {
            System.err.println(e.getMessage());
            System.err.println(USAGE);
            parser.printUsage(System.err);
            return;
        }
        if (help) {
            System.err.println(USAGE);
            parser.printUsage(System.err);
            return;
        }
        if (queryFiles.isEmpty()) {
            System.err.println("Error: no query sample files provided.");
            System.err.println(USAGE);
            return;
        }

        // Validate top-level mode.
        boolean useRefPanel = (refPanelFile != null);
        boolean haveRefBetasAndGroups = (refBetasArg != null && refGroupsFile != null);
        boolean haveOneOfRefInputs = (refBetasArg != null || refGroupsFile != null);
        if (haveOneOfRefInputs && !haveRefBetasAndGroups) {
            System.err.println("Error: provide both -refBetas and -refGroups together.");
            System.err.println(USAGE);
            return;
        }

        // Validate mode: either -markerRegions or -cgiShoreRegions
        // (unless -refPanel is used, which already carries the marker coordinates)
        if (markerRegionsFile == null && cgiShoreBed == null && !useRefPanel) {
            System.err.println("Error: provide either -markerRegions, -cgiShoreRegions, or -refPanel.");
            System.err.println(USAGE);
            return;
        }

        // CpG index is always needed for parsing query .beta / .prediction.bed
        // files. When -refPanel is used, -cpgIndex is still required for queries.
        if (cpgIndexFile == null) {
            System.err.println("Error: -cpgIndex is required for parsing query samples.");
            System.err.println(USAGE);
            return;
        }
        log.info("Loading CpG index...");
        CpgIndex cpgIndex = loadCpgIndex(cpgIndexFile);

        List<Window> selectedWindows;
        double[][] refSelected;
        List<String> cellTypes;

        if (useRefPanel) {
            // ===== Reference panel mode: load pre-aggregated panel directly =====
            log.info("Loading pre-aggregated reference panel: {}", refPanelFile);
            Object[] panelData = loadReferencePanel(refPanelFile, cpgIndex);
            selectedWindows = (List<Window>) panelData[0];
            double[][] refMatrix = (double[][]) panelData[1];
            cellTypes = (List<String>) panelData[2];
            this.markerTargets = (List<String>) panelData[3];
            log.info("Reference panel: {} markers x {} cell types", selectedWindows.size(), cellTypes.size());

            // Binarize reference
            refSelected = new double[selectedWindows.size()][cellTypes.size()];
            for (int i = 0; i < selectedWindows.size(); i++) {
                for (int j = 0; j < cellTypes.size(); j++) {
                    double v = refMatrix[i][j];
                    refSelected[i][j] = Double.isNaN(v) || v < binarizeThreshold ? 0.0 : 1.0;
                }
            }

        } else {
            if (markerRegionsFile != null) {
                // ===== Marker regions mode =====
                double[][] refMatrix;
                if (haveRefBetasAndGroups) {
                    // Legacy behavior: compute reference from .beta files.
                    List<String> refBetaPaths = parseRefBetas(refBetasArg);
                    Map<String, String> sampleToGroup = loadGroupsFile(refGroupsFile);
                    log.info("Loaded {} reference beta files, {} groups",
                            refBetaPaths.size(), new HashSet<>(sampleToGroup.values()).size());
                    cellTypes = new ArrayList<>(new TreeSet<>(sampleToGroup.values()));

                    log.info("Marker regions mode: loading regions from {}", markerRegionsFile);
                    selectedWindows = loadMarkerRegions(markerRegionsFile);
                    log.info("Loaded {} marker regions", selectedWindows.size());

                    log.info("Computing reference methylation at marker regions (mode: {})...", replicateMode);
                    refMatrix = loadReferenceMethylation(
                            refBetaPaths, sampleToGroup, cellTypes, selectedWindows, cpgIndex);
                } else {
                    // New behavior: if marker atlas has embedded values, use directly.
                    log.info("Marker regions mode: trying embedded reference values from {}", markerRegionsFile);
                    Object[] panelData = loadReferencePanel(markerRegionsFile, cpgIndex);
                    selectedWindows = (List<Window>) panelData[0];
                    refMatrix = (double[][]) panelData[1];
                    cellTypes = (List<String>) panelData[2];
                    this.markerTargets = (List<String>) panelData[3];
                    if (cellTypes == null || cellTypes.isEmpty()) {
                        System.err.println("Error: -markerRegions file has no embedded cell-type value columns. "
                                + "Provide -refBetas/-refGroups or a marker atlas with per-cell-type values.");
                        System.err.println(USAGE);
                        return;
                    }
                    log.info("Embedded marker atlas reference: {} markers x {} cell types",
                            selectedWindows.size(), cellTypes.size());
                }

                // Binarize reference
                refSelected = new double[selectedWindows.size()][cellTypes.size()];
                for (int i = 0; i < selectedWindows.size(); i++) {
                    for (int j = 0; j < cellTypes.size(); j++) {
                        double v = refMatrix[i][j];
                        refSelected[i][j] = Double.isNaN(v) || v < binarizeThreshold ? 0.0 : 1.0;
                    }
                }

            } else {
                // ===== Original mode: tile CGI+shore, filter by variability =====
                if (!haveRefBetasAndGroups) {
                    System.err.println("Error: -cgiShoreRegions mode requires -refBetas and -refGroups.");
                    System.err.println(USAGE);
                    return;
                }
                List<String> refBetaPaths = parseRefBetas(refBetasArg);
                Map<String, String> sampleToGroup = loadGroupsFile(refGroupsFile);
                log.info("Loaded {} reference beta files, {} groups",
                        refBetaPaths.size(), new HashSet<>(sampleToGroup.values()).size());
                cellTypes = new ArrayList<>(new TreeSet<>(sampleToGroup.values()));

                log.info("Generating {}bp windows within CGI+shore regions...", windowSize);
                List<Window> windows = generateWindows(cgiShoreBed, cpgIndex);
                log.info("Generated {} windows", windows.size());

                log.info("Loading reference methylation data (mode: {})...", replicateMode);
                double[][] refMatrix = loadReferenceMethylation(
                        refBetaPaths, sampleToGroup, cellTypes, windows, cpgIndex);

                log.info("Filtering windows (minCoverage={}, topVariable={}%)...",
                        minCoverage, topVariablePercent * 100);
                int[] selectedIndices = filterAndSelectWindows(refMatrix, cellTypes.size());
                log.info("Selected {} windows after filtering", selectedIndices.length);

                if (selectedIndices.length == 0) {
                    log.error("No windows passed filtering. Try lowering -minCoverage or -topVariablePercent.");
                    return;
                }

                refSelected = new double[selectedIndices.length][cellTypes.size()];
                selectedWindows = new ArrayList<>();
                for (int i = 0; i < selectedIndices.length; i++) {
                    selectedWindows.add(windows.get(selectedIndices[i]));
                    for (int j = 0; j < cellTypes.size(); j++) {
                        double v = refMatrix[selectedIndices[i]][j];
                        refSelected[i][j] = v < binarizeThreshold ? 0.0 : 1.0;
                    }
                }
            }
        }

        // Step 6 & 7: Process each query sample
        List<String> sampleNames = new ArrayList<>();
        List<double[]> allWeights = new ArrayList<>();
        List<BootstrapResult> allBoot = new ArrayList<>();  // one per sample when bootstrap enabled
        List<PermutationResult> allPerm = new ArrayList<>();  // one per sample when permutation enabled

        for (String queryFile : queryFiles) {
            log.info("Processing query: {}", queryFile);
            double[] queryValues = loadQuerySample(queryFile, selectedWindows, cpgIndex);

            // Binarize query
            for (int i = 0; i < queryValues.length; i++) {
                if (Double.isNaN(queryValues[i])) {
                    queryValues[i] = 0.0; // treat missing as unmethylated
                } else {
                    queryValues[i] = queryValues[i] < binarizeThreshold ? 0.0 : 1.0;
                }
            }

            double[] weights;
            if ("NNLS".equalsIgnoreCase(solver)) {
                weights = solveNNLS(refSelected, queryValues);
            } else {
                weights = solveQP(refSelected, queryValues);
            }

            sampleNames.add(new File(queryFile).getName());
            allWeights.add(weights);

            if (bootstrap) {
                log.info("Running bootstrap ({} replicates, {} threads, stratified={})...",
                        nBootstrap, bootstrapThreads, bootstrapStratified);
                BootstrapResult br = runBootstrap(refSelected, queryValues, weights);
                allBoot.add(br);
            }
            if (permutationTest) {
                log.info("Running column-permutation test ({} permutations per cell type, {} threads)...",
                        nPermutations, bootstrapThreads);
                PermutationResult pr = runPermutationTest(refSelected, queryValues, weights);
                allPerm.add(pr);
            }
        }

        // Step 8: Output — two schemas, chosen by whether bootstrap was run.
        PrintWriter out = outputFile != null ? new PrintWriter(new FileWriter(outputFile)) : new PrintWriter(System.out);

        if (bootstrap || permutationTest) {
            // Long-form output: one row per (sample, cell_type) with stats.
            //
            // When both -bootstrap and -permutationTest are on:
            //   - CI comes from bootstrap
            //   - p-value / q-value / significant come from permutation
            //     (permutation p has better resolution at small values)
            // When only one is on, that source supplies all three.
            double alpha = 1.0 - ciLevel;
            double loPct = 100.0 * (alpha / 2.0);
            double hiPct = 100.0 * (1.0 - alpha / 2.0);
            String pSource = permutationTest ? "permutation" : "bootstrap";
            out.println("sample\tcell_type\tproportion\tCI_lower\tCI_upper\tp_value\tq_value\tsignificant\tp_source\tn_replicates");
            for (int s = 0; s < sampleNames.size(); s++) {
                String sname = sampleNames.get(s);
                double[] w = allWeights.get(s);
                BootstrapResult br = bootstrap ? allBoot.get(s) : null;
                PermutationResult pr = permutationTest ? allPerm.get(s) : null;
                for (int c = 0; c < cellTypes.size(); c++) {
                    double prop = w[c] < 0.001 ? 0.0 : w[c];
                    double ciLo = (br != null) ? br.ciLower[c] : Double.NaN;
                    double ciHi = (br != null) ? br.ciUpper[c] : Double.NaN;
                    double p = (pr != null) ? pr.pValue[c] : br.pValue[c];
                    double q = (pr != null) ? pr.qValue[c] : br.qValue[c];
                    String sig = (q <= fdrAlpha) ? "YES" : "NO";
                    int nRep = (pr != null) ? pr.nPermutations : nBootstrap;
                    if (Double.isNaN(ciLo)) {
                        out.printf(
                                "%s\t%s\t%.4f\tNA\tNA\t%.4g\t%.4g\t%s\t%s\t%d%n",
                                sname, cellTypes.get(c), prop,
                                p, q, sig, pSource, nRep);
                    } else {
                        out.printf(
                                "%s\t%s\t%.4f\t%.4f\t%.4f\t%.4g\t%.4g\t%s\t%s\t%d%n",
                                sname, cellTypes.get(c), prop,
                                ciLo, ciHi,
                                p, q, sig, pSource, nRep);
                    }
                }
            }
            log.info("Stats output: CI {} at [{}%, {}%], p-values from {}, FDR threshold {}",
                    bootstrap ? "from bootstrap" : "(not computed)", loPct, hiPct, pSource, fdrAlpha);
        } else {
            // Wide-form output (legacy): cell_type | sample1 | sample2 | ...
            out.print("cell_type");
            for (String name : sampleNames) {
                out.print("\t" + name);
            }
            out.println();
            for (int c = 0; c < cellTypes.size(); c++) {
                out.print(cellTypes.get(c));
                for (double[] weights : allWeights) {
                    double w = weights[c];
                    out.printf("\t%.4f", w < 0.001 ? 0.0 : w);
                }
                out.println();
            }
        }

        out.flush();
        if (outputFile != null) out.close();
        log.info("Done.");
    }

    // ========================= CpG Index Loading =========================

    private CpgIndex loadCpgIndex(String path) throws IOException {
        LinkedHashMap<String, ArrayList<Integer>> chrToPositions = new LinkedHashMap<>();
        InputStream input = path.endsWith(".gz")
                ? new GZIPInputStream(new FileInputStream(path))
                : new FileInputStream(path);
        try (BufferedReader br = new BufferedReader(new InputStreamReader(input, StandardCharsets.UTF_8))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.isEmpty() || line.startsWith("#")) continue;
                String[] parts = line.split("\t");
                if (parts.length < 2) continue;
                String chr = parts[0];
                int start;
                try {
                    start = Integer.parseInt(parts[1]);
                } catch (NumberFormatException e) {
                    continue;
                }
                chrToPositions.computeIfAbsent(chr, k -> new ArrayList<>()).add(start);
            }
        }

        LinkedHashMap<String, int[]> chrPositions = new LinkedHashMap<>();
        HashMap<String, Integer> chrOffsets = new HashMap<>();
        int totalSites = 0;
        for (Map.Entry<String, ArrayList<Integer>> entry : chrToPositions.entrySet()) {
            ArrayList<Integer> positions = entry.getValue();
            Collections.sort(positions);
            // Deduplicate
            int[] posArray = positions.stream().mapToInt(Integer::intValue).distinct().toArray();
            chrOffsets.put(entry.getKey(), totalSites);
            chrPositions.put(entry.getKey(), posArray);
            totalSites += posArray.length;
        }
        log.info("CpG index: {} sites across {} chromosomes", totalSites, chrPositions.size());
        return new CpgIndex(chrPositions, chrOffsets, totalSites);
    }

    // ========================= Marker Regions Loading =========================

    /**
     * Load pre-defined marker regions from an atlas TSV or BED file.
     * Extracts only the genomic coordinates (chr, start, end, startCpG, endCpG).
     *
     * Supports two formats:
     *   - Atlas TSV: chr start end startCpG endCpG target name direction [cell type cols...]
     *   - BED file:  chr start end startCpG endCpG [optional extra cols]
     *
     * Auto-detects format by checking if column 1 is numeric (BED) or has a header.
     */

    /**
     * Load a pre-aggregated reference panel TSV.
     *
     * Format (generated by generate_cgi_shore_markers.py stage 4):
     *   chrom  start  end  CellType1       CellType2       ...
     *   chr1   1000   1500 125/250         30/250          ...
     *
     * Each cell value is either "methylated_count/total_count" (detected by
     * the presence of "/") or a plain float beta value (0.85). Both formats
     * are handled transparently.
     *
     * Returns Object[] { List<Window>, double[][], List<String> }:
     *   [0] windows — marker regions as Window objects
     *   [1] refMatrix — (nMarkers x nCellTypes) methylation matrix
     *   [2] cellTypes — ordered list of cell type names from the header
     */
    private int findHeaderColumnIndex(String[] header, String... names) {
        Set<String> target = new HashSet<>();
        for (String n : names) {
            target.add(n.toLowerCase(Locale.ROOT));
        }
        for (int i = 0; i < header.length; i++) {
            String h = header[i].trim().toLowerCase(Locale.ROOT);
            if (h.startsWith("#")) h = h.substring(1);
            if (target.contains(h)) return i;
        }
        return -1;
    }

    private Object[] loadReferencePanel(String path, CpgIndex cpgIndex) throws IOException {
        BufferedReader br;
        if (path.endsWith(".gz")) {
            br = new BufferedReader(new InputStreamReader(
                    new GZIPInputStream(new FileInputStream(path)), StandardCharsets.UTF_8));
        } else {
            br = new BufferedReader(new FileReader(path));
        }

        List<Window> windows = new ArrayList<>();
        List<double[]> rows = new ArrayList<>();
        List<String> cellTypes = null;
        Set<String> seen = new HashSet<>();
        int skippedNonAutosome = 0;
        int skippedDuplicate = 0;
        int skippedNoCpg = 0;
        int parsedRows = 0;
        int coordParseErrors = 0;

        int chrCol = 0;
        int startCol = 1;
        int endCol = 2;
        int startCpgCol = -1;
        int endCpgCol = -1;
        int firstValueCol = 3;
        int targetCol = -1;
        List<String> markerTargets = new ArrayList<>();

        try {
            String line;
            boolean first = true;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#")) continue;

                String[] parts = line.split("\t");

                if (first) {
                    // Header row: either panel-style (chrom/start/end/...) or
                    // atlas-style (chr/start/end/startCpG/endCpG/target/name/direction/...).
                    first = false;
                    // Check if first column is numeric (headerless BED) or a label
                    try {
                        Integer.parseInt(parts[1]);
                        // Looks numeric → no header, parse as data
                    } catch (NumberFormatException e) {
                        // Header present: detect coordinate and value columns.
                        int tmpChr = findHeaderColumnIndex(parts, "chrom", "chr", "#chr");
                        int tmpStart = findHeaderColumnIndex(parts, "start");
                        int tmpEnd = findHeaderColumnIndex(parts, "end");
                        if (tmpChr >= 0 && tmpStart >= 0 && tmpEnd >= 0) {
                            chrCol = tmpChr;
                            startCol = tmpStart;
                            endCol = tmpEnd;
                        }

                        startCpgCol = findHeaderColumnIndex(parts, "startcpg", "start_cpg");
                        endCpgCol = findHeaderColumnIndex(parts, "endcpg", "end_cpg");
                        // `target` column carries the primary cell-type label per marker
                        // (used by stratified bootstrap to resample within cell types).
                        targetCol = findHeaderColumnIndex(parts, "target");
                        int directionCol = findHeaderColumnIndex(parts, "direction");
                        if (directionCol >= 0 && directionCol + 1 < parts.length) {
                            firstValueCol = directionCol + 1;
                        } else {
                            firstValueCol = Math.max(Math.max(chrCol, startCol), endCol) + 1;
                        }

                        // Extract cell-type names from the value columns.
                        cellTypes = new ArrayList<>();
                        for (int i = firstValueCol; i < parts.length; i++) {
                            cellTypes.add(parts[i]);
                        }
                        continue;
                    }
                }

                if (parts.length <= Math.max(endCol, firstValueCol)) continue;

                String chr;
                int start;
                int end;
                try {
                    chr = parts[chrCol];
                    start = Integer.parseInt(parts[startCol]);
                    end = Integer.parseInt(parts[endCol]);
                } catch (Exception ex) {
                    coordParseErrors++;
                    continue;
                }
                parsedRows++;

                // Keep refPanel behavior consistent with -markerRegions mode:
                // skip non-autosome chromosomes and deduplicate by coordinates.
                if (chr.contains("_") || chr.equals("chrX") || chr.equals("chrY") || chr.equals("chrM")) {
                    skippedNonAutosome++;
                    continue;
                }
                String key = chr + ":" + start + "-" + end;
                if (!seen.add(key)) {
                    skippedDuplicate++;
                    continue;
                }

                int startCpgIdx = -1;
                int endCpgExclusive = 0;
                // If atlas carries startCpG/endCpG, use them directly to keep
                // marker-based behavior consistent.
                if (startCpgCol >= 0 && endCpgCol >= 0
                        && startCpgCol < parts.length && endCpgCol < parts.length) {
                    try {
                        int s = Integer.parseInt(parts[startCpgCol]);
                        int e = Integer.parseInt(parts[endCpgCol]);
                        if (s > 0 && e >= s) {
                            startCpgIdx = s;
                            endCpgExclusive = e;
                        }
                    } catch (NumberFormatException ignored) {
                        // fall through to coordinate-derived CpG indices
                    }
                }

                // Otherwise derive CpG indices from coordinates.
                if (endCpgExclusive == 0) {
                    int endCpgLast = cpgIndex.getLastCpgIndexBefore(chr, end);
                    int s = cpgIndex.getFirstCpgIndexAtOrAfter(chr, start);
                    if (s > 0 && endCpgLast >= s) {
                        startCpgIdx = s;
                        endCpgExclusive = endCpgLast + 1;
                    }
                }

                if (endCpgExclusive == 0) {
                    skippedNoCpg++;
                    continue;
                }
                windows.add(new Window(chr, start, end, startCpgIdx, endCpgExclusive));

                // Capture the `target` cell-type label for this marker row (or null if absent).
                String targetLabel = null;
                if (targetCol >= 0 && targetCol < parts.length) {
                    targetLabel = parts[targetCol].trim();
                    if (targetLabel.isEmpty()) targetLabel = null;
                }
                markerTargets.add(targetLabel);

                int nCt = (cellTypes != null) ? cellTypes.size() : Math.max(0, parts.length - firstValueCol);
                double[] vals = new double[nCt];
                Arrays.fill(vals, Double.NaN);
                for (int i = 0; i < nCt; i++) {
                    int col = firstValueCol + i;
                    if (col >= parts.length) break;
                    String cell = parts[col].trim();
                    if (cell.contains("/")) {
                        // Count ratio format: "125/250"
                        String[] kn = cell.split("/", 2);
                        try {
                            long k = Long.parseLong(kn[0]);
                            long n = Long.parseLong(kn[1]);
                            // Keep refPanel mode consistent with
                            // loadReferenceMethylation(): enforce minCoverage.
                            vals[i] = (n >= minCoverage) ? (double) k / n : Double.NaN;
                        } catch (NumberFormatException e) {
                            vals[i] = Double.NaN;
                        }
                    } else {
                        // Plain float format: "0.85"
                        try {
                            vals[i] = Double.parseDouble(cell);
                        } catch (NumberFormatException e) {
                            vals[i] = Double.NaN;
                        }
                    }
                }
                rows.add(vals);
            }
        } finally {
            br.close();
        }

        if (cellTypes == null && !rows.isEmpty()) {
            // No header detected — generate placeholder cell type names
            cellTypes = new ArrayList<>();
            for (int i = 0; i < rows.get(0).length; i++) {
                cellTypes.add("CellType" + (i + 1));
            }
        }

        int nMarkers = rows.size();
        int nCt = cellTypes != null ? cellTypes.size() : 0;
        double[][] refMatrix = new double[nMarkers][nCt];
        for (int i = 0; i < nMarkers; i++) {
            double[] row = rows.get(i);
            for (int j = 0; j < Math.min(row.length, nCt); j++) {
                refMatrix[i][j] = row[j];
            }
        }

        log.info(
                "Reference panel parsing: {} data rows -> {} kept "
                        + "(skipped {} non-autosome, {} duplicate, {} no-CpG, {} coord-parse)",
                parsedRows, nMarkers, skippedNonAutosome, skippedDuplicate, skippedNoCpg, coordParseErrors
        );
        if (targetCol >= 0) {
            long withTarget = markerTargets.stream().filter(Objects::nonNull).count();
            long distinct = markerTargets.stream().filter(Objects::nonNull).distinct().count();
            log.info("Reference panel `target` column: {} markers labeled, {} distinct cell types",
                    withTarget, distinct);
        } else {
            log.info("Reference panel has no `target` column — stratified bootstrap will "
                    + "fall back to uniform if requested.");
        }

        return new Object[]{windows, refMatrix, cellTypes, markerTargets};
    }

    private List<Window> loadMarkerRegions(String path) throws IOException {
        List<Window> windows = new ArrayList<>();

        BufferedReader br;
        if (path.endsWith(".gz")) {
            br = new BufferedReader(new InputStreamReader(
                    new GZIPInputStream(new FileInputStream(path)), StandardCharsets.UTF_8));
        } else {
            br = new BufferedReader(new FileReader(path));
        }

        try {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.isEmpty() || line.startsWith("#")) continue;
                String[] parts = line.split("\t");
                if (parts.length < 5) continue;

                // Skip header row (if column 1 is not numeric)
                try {
                    Integer.parseInt(parts[1]);
                } catch (NumberFormatException e) {
                    continue; // header row
                }

                String chr = parts[0];
                int start, end, startCpG, endCpG;
                try {
                    start = Integer.parseInt(parts[1]);
                    end = Integer.parseInt(parts[2]);
                    startCpG = Integer.parseInt(parts[3]);
                    endCpG = Integer.parseInt(parts[4]);
                } catch (NumberFormatException e) {
                    continue;
                }

                // Skip non-autosome
                if (chr.contains("_") || chr.equals("chrX") || chr.equals("chrY") || chr.equals("chrM")) {
                    continue;
                }

                windows.add(new Window(chr, start, end, startCpG, endCpG));
            }
        } finally {
            br.close();
        }

        // Deduplicate by coordinates
        Set<String> seen = new HashSet<>();
        List<Window> unique = new ArrayList<>();
        for (Window w : windows) {
            String key = w.chr + ":" + w.start + "-" + w.end;
            if (seen.add(key)) {
                unique.add(w);
            }
        }

        log.info("Loaded {} unique marker regions from {}", unique.size(), path);
        return unique;
    }

    // ========================= Window Generation =========================

    private List<Window> generateWindows(String bedPath, CpgIndex cpgIndex) throws IOException {
        List<Window> windows = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(bedPath))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.isEmpty() || line.startsWith("#")) continue;
                String[] parts = line.split("\t");
                String chr = parts[0];
                int regionStart = Integer.parseInt(parts[1]);
                int regionEnd = Integer.parseInt(parts[2]);

                // Skip non-autosome chromosomes
                if (chr.contains("_") || chr.equals("chrX") || chr.equals("chrY") || chr.equals("chrM")) {
                    continue;
                }

                // Tile into non-overlapping windows
                for (int wStart = regionStart; wStart + windowSize <= regionEnd; wStart += windowSize) {
                    int wEnd = wStart + windowSize;
                    int startIdx = cpgIndex.getFirstCpgIndexAtOrAfter(chr, wStart);
                    int endIdx = cpgIndex.getLastCpgIndexBefore(chr, wEnd);
                    if (startIdx > 0 && endIdx > 0 && endIdx >= startIdx) {
                        windows.add(new Window(chr, wStart, wEnd, startIdx, endIdx + 1));
                    }
                }
            }
        }
        return windows;
    }

    // ========================= Reference Data Loading =========================

    private List<String> parseRefBetas(String arg) throws IOException {
        if (arg.endsWith(".txt")) {
            // Read file list
            List<String> paths = new ArrayList<>();
            try (BufferedReader br = new BufferedReader(new FileReader(arg))) {
                String line;
                while ((line = br.readLine()) != null) {
                    line = line.trim();
                    if (!line.isEmpty() && !line.startsWith("#")) {
                        paths.add(line);
                    }
                }
            }
            return paths;
        } else {
            return Arrays.asList(arg.split(","));
        }
    }

    private Map<String, String> loadGroupsFile(String path) throws IOException {
        Map<String, String> sampleToGroup = new LinkedHashMap<>();
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String header = br.readLine(); // skip header
            String line;
            while ((line = br.readLine()) != null) {
                if (line.isEmpty() || line.startsWith("#")) continue;
                String[] parts = line.split(",");
                if (parts.length >= 2) {
                    String name = parts[0].trim();
                    String group = parts[1].trim();
                    // Strip file extensions from name
                    name = name.replaceAll("\\.(pat\\.gz|beta|pat)$", "");
                    sampleToGroup.put(name, group);
                }
            }
        }
        return sampleToGroup;
    }

    /**
     * Load reference methylation: read each .beta file, collapse to windows,
     * aggregate by cell type.
     */
    private double[][] loadReferenceMethylation(
            List<String> betaPaths, Map<String, String> sampleToGroup,
            List<String> cellTypes, List<Window> windows, CpgIndex cpgIndex) throws IOException {

        int numWindows = windows.size();
        int numCellTypes = cellTypes.size();
        Map<String, Integer> ctIndex = new HashMap<>();
        for (int i = 0; i < cellTypes.size(); i++) ctIndex.put(cellTypes.get(i), i);

        if ("aggregate".equalsIgnoreCase(replicateMode)) {
            // Sum counts across replicates, then compute ratio
            long[][] aggMethy = new long[numWindows][numCellTypes];
            long[][] aggTotal = new long[numWindows][numCellTypes];

            for (String betaPath : betaPaths) {
                String sampleName = betaNameToSampleName(betaPath);
                String group = sampleToGroup.get(sampleName);
                if (group == null) {
                    log.warn("Sample {} not found in groups file, skipping", sampleName);
                    continue;
                }
                int ci = ctIndex.getOrDefault(group, -1);
                if (ci < 0) continue;

                int[][] windowCounts = loadBetaFileToWindows(betaPath, windows, cpgIndex);
                for (int w = 0; w < numWindows; w++) {
                    aggMethy[w][ci] += windowCounts[w][0];
                    aggTotal[w][ci] += windowCounts[w][1];
                }
                log.info("  Loaded {}: {} ({})", sampleName, group, betaPath);
            }

            double[][] result = new double[numWindows][numCellTypes];
            for (int w = 0; w < numWindows; w++) {
                for (int c = 0; c < numCellTypes; c++) {
                    if (aggTotal[w][c] >= minCoverage) {
                        result[w][c] = (double) aggMethy[w][c] / aggTotal[w][c];
                    } else {
                        result[w][c] = Double.NaN;
                    }
                }
            }
            return result;

        } else {
            // Average mode: compute per-sample ratio, then average
            Map<String, List<double[]>> groupVectors = new HashMap<>();
            for (String ct : cellTypes) groupVectors.put(ct, new ArrayList<>());

            for (String betaPath : betaPaths) {
                String sampleName = betaNameToSampleName(betaPath);
                String group = sampleToGroup.get(sampleName);
                if (group == null) {
                    log.warn("Sample {} not found in groups file, skipping", sampleName);
                    continue;
                }

                int[][] windowCounts = loadBetaFileToWindows(betaPath, windows, cpgIndex);
                double[] ratios = new double[numWindows];
                for (int w = 0; w < numWindows; w++) {
                    if (windowCounts[w][1] >= minCoverage) {
                        ratios[w] = (double) windowCounts[w][0] / windowCounts[w][1];
                    } else {
                        ratios[w] = Double.NaN;
                    }
                }
                groupVectors.get(group).add(ratios);
                log.info("  Loaded {}: {} ({})", sampleName, group, betaPath);
            }

            double[][] result = new double[numWindows][numCellTypes];
            for (int c = 0; c < numCellTypes; c++) {
                List<double[]> vectors = groupVectors.get(cellTypes.get(c));
                for (int w = 0; w < numWindows; w++) {
                    double sum = 0;
                    int count = 0;
                    for (double[] v : vectors) {
                        if (!Double.isNaN(v[w])) {
                            sum += v[w];
                            count++;
                        }
                    }
                    result[w][c] = count > 0 ? sum / count : Double.NaN;
                }
            }
            return result;
        }
    }

    private String betaNameToSampleName(String path) {
        String name = new File(path).getName();
        // Strip .beta or .lbeta extension
        if (name.endsWith(".beta")) name = name.substring(0, name.length() - 5);
        else if (name.endsWith(".lbeta")) name = name.substring(0, name.length() - 6);
        return name;
    }

    // ========================= Beta File Reading =========================

    /**
     * Read a binary .beta file and collapse to per-window [methylated, total] counts.
     * Beta format: NR_SITES rows x 2 columns of uint8 (methylated, total).
     */
    private int[][] loadBetaFileToWindows(String betaPath, List<Window> windows, CpgIndex cpgIndex)
            throws IOException {
        int numWindows = windows.size();
        int[][] result = new int[numWindows][2]; // [methy, total]

        try (FileInputStream fis = new FileInputStream(betaPath)) {
            byte[] data = fis.readAllBytes();
            int numSites = data.length / 2;

            for (int w = 0; w < numWindows; w++) {
                Window win = windows.get(w);
                int startIdx = win.startCpgIdx - 1; // convert to 0-based
                int endIdx = win.endCpgIdx - 1;     // exclusive

                int methy = 0, total = 0;
                for (int i = startIdx; i < endIdx && i < numSites; i++) {
                    int m = data[i * 2] & 0xFF;     // unsigned byte
                    int t = data[i * 2 + 1] & 0xFF; // unsigned byte
                    methy += m;
                    total += t;
                }
                result[w][0] = methy;
                result[w][1] = total;
            }
        }
        return result;
    }

    // ========================= Window Filtering =========================

    /**
     * Filter windows: remove NaN, select top variable percent.
     * Returns indices into the original windows list.
     */
    private int[] filterAndSelectWindows(double[][] refMatrix, int numCellTypes) {
        int numWindows = refMatrix.length;
        List<int[]> validWithSd = new ArrayList<>(); // [index, sd*10000]

        for (int w = 0; w < numWindows; w++) {
            boolean hasNaN = false;
            double sum = 0, sumSq = 0;
            for (int c = 0; c < numCellTypes; c++) {
                if (Double.isNaN(refMatrix[w][c])) {
                    hasNaN = true;
                    break;
                }
                sum += refMatrix[w][c];
                sumSq += refMatrix[w][c] * refMatrix[w][c];
            }
            if (hasNaN) continue;

            double mean = sum / numCellTypes;
            double variance = sumSq / numCellTypes - mean * mean;
            double sd = Math.sqrt(Math.max(0, variance));
            validWithSd.add(new int[]{w, (int) (sd * 1000000)});
        }

        log.info("  {} windows passed coverage filter (of {})", validWithSd.size(), numWindows);

        if (validWithSd.isEmpty()) return new int[0];

        // Sort by SD descending
        validWithSd.sort((a, b) -> Integer.compare(b[1], a[1]));

        // Keep top percent
        int topN = Math.max(1, (int) (validWithSd.size() * topVariablePercent));
        log.info("  Keeping top {} most variable windows (top {:.1f}%)",
                topN, topVariablePercent * 100);

        int[] selected = new int[topN];
        for (int i = 0; i < topN; i++) {
            selected[i] = validWithSd.get(i)[0];
        }
        Arrays.sort(selected); // restore genomic order
        return selected;
    }

    // ========================= Query Sample Loading =========================

    /**
     * Load query sample data from .beta or .prediction.bed.gz file.
     * Returns per-window methylation density for the selected windows only.
     */
    private double[] loadQuerySample(String queryFile, List<Window> windows, CpgIndex cpgIndex)
            throws IOException {
        if (queryFile.endsWith(".beta") || queryFile.endsWith(".lbeta")) {
            return loadQueryFromBeta(queryFile, windows, cpgIndex);
        } else if (isPredictionPath(queryFile)) {
            return loadQueryFromPredictionOverlap(queryFile, windows);
        } else if (queryFile.endsWith(".bed.gz") || queryFile.endsWith(".bed")) {
            return loadQueryFromBed(queryFile, windows, cpgIndex);
        } else if (queryFile.endsWith(".txt.gz") || queryFile.endsWith(".txt")) {
            // FinaleMe prediction output can also use .txt.gz extension
            return loadQueryFromPredictionOverlap(queryFile, windows);
        } else {
            throw new IllegalArgumentException(
                    "Unknown query file format: " + queryFile
                            + ". Expected .beta, .prediction.bed.gz, .prediction.txt.gz, or 6+2 BED.");
        }
    }

    private double[] loadQueryFromBeta(String betaPath, List<Window> windows, CpgIndex cpgIndex)
            throws IOException {
        int[][] counts = loadBetaFileToWindows(betaPath, windows, cpgIndex);
        double[] result = new double[windows.size()];
        for (int w = 0; w < windows.size(); w++) {
            if (counts[w][1] >= minCoverage) {
                result[w] = (double) counts[w][0] / counts[w][1];
            } else {
                result[w] = Double.NaN;
            }
        }
        return result;
    }

    private boolean isPredictionBedPath(String path) {
        String lower = path.toLowerCase(Locale.ROOT);
        return lower.endsWith(".prediction.bed") || lower.endsWith(".prediction.bed.gz");
    }

    private boolean isPredictionPath(String path) {
        String lower = path.toLowerCase(Locale.ROOT);
        return lower.endsWith(".prediction.bed") || lower.endsWith(".prediction.bed.gz")
                || lower.endsWith(".prediction.txt") || lower.endsWith(".prediction.txt.gz");
    }

    /**
     * FinaleMe prediction.bed(.gz) path.
     * Uses legacy genomic interval overlap (start/end) by design.
     */
    private double[] loadQueryFromPredictionOverlap(String predFile, List<Window> windows)
            throws IOException {
        int numWindows = windows.size();
        long[] methyCounts = new long[numWindows];
        long[] totalCounts = new long[numWindows];

        // Build interval lookup: chr -> sorted list of (start, end, windowIndex)
        Map<String, List<int[]>> chrWindowMap = new HashMap<>();
        for (int w = 0; w < numWindows; w++) {
            Window win = windows.get(w);
            chrWindowMap.computeIfAbsent(win.chr, k -> new ArrayList<>())
                    .add(new int[]{win.start, win.end, w});
        }

        InputStream input = predFile.endsWith(".gz")
                ? new GZIPInputStream(new FileInputStream(predFile))
                : new FileInputStream(predFile);
        try (BufferedReader br = new BufferedReader(new InputStreamReader(input, StandardCharsets.UTF_8))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.startsWith("#") || line.isEmpty()) continue;
                String[] parts = line.split("\t");
                if (parts.length < 6) continue;

                String chr = parts[0];
                int pos;
                double methyCount, totalCount;
                try {
                    pos = Integer.parseInt(parts[1]);
                    methyCount = Double.parseDouble(parts[4]); // methy_count_predict
                    totalCount = Double.parseDouble(parts[5]); // total_count_predict
                } catch (NumberFormatException e) {
                    continue;
                }

                List<int[]> chrWindows = chrWindowMap.get(chr);
                if (chrWindows == null) continue;

                // Find which window this CpG falls in (linear scan; windows are sorted)
                for (int[] wInfo : chrWindows) {
                    if (pos >= wInfo[0] && pos < wInfo[1]) {
                        int wIdx = wInfo[2];
                        methyCounts[wIdx] += (long) methyCount;
                        totalCounts[wIdx] += (long) totalCount;
                        break;
                    }
                }
            }
        }

        double[] result = new double[numWindows];
        for (int w = 0; w < numWindows; w++) {
            if (totalCounts[w] >= minCoverage) {
                result[w] = (double) methyCounts[w] / totalCounts[w];
            } else {
                result[w] = Double.NaN;
            }
        }
        return result;
    }

    private String resolveChrForCpgIndex(String chr, CpgIndex cpgIndex) {
        if (cpgIndex.chrPositions.containsKey(chr)) {
            return chr;
        }
        if (chr.startsWith("chr")) {
            String alt = chr.substring(3);
            if (cpgIndex.chrPositions.containsKey(alt)) {
                return alt;
            }
        } else {
            String alt = "chr" + chr;
            if (cpgIndex.chrPositions.containsKey(alt)) {
                return alt;
            }
        }
        return chr;
    }

    private int getGlobalCpgIndexExact(CpgIndex cpgIndex, String chr, int pos) {
        String resolvedChr = resolveChrForCpgIndex(chr, cpgIndex);
        int[] positions = cpgIndex.chrPositions.get(resolvedChr);
        Integer offset = cpgIndex.chrOffsets.get(resolvedChr);
        if (positions == null || offset == null) {
            return -1;
        }
        int idx = Arrays.binarySearch(positions, pos);
        if (idx < 0) {
            return -1;
        }
        return offset + idx + 1; // 1-based global CpG index
    }

    private Map<String, WindowCpgLookup> buildWindowCpgLookups(List<Window> windows, CpgIndex cpgIndex) {
        Map<String, List<int[]>> byChr = new HashMap<>();
        for (int w = 0; w < windows.size(); w++) {
            Window win = windows.get(w);
            if (win.startCpgIdx <= 0 || win.endCpgIdx <= win.startCpgIdx) {
                continue;
            }
            String chr = resolveChrForCpgIndex(win.chr, cpgIndex);
            byChr.computeIfAbsent(chr, k -> new ArrayList<>())
                    .add(new int[]{win.startCpgIdx, win.endCpgIdx, w});
        }

        Map<String, WindowCpgLookup> out = new HashMap<>();
        for (Map.Entry<String, List<int[]>> e : byChr.entrySet()) {
            out.put(e.getKey(), new WindowCpgLookup(e.getValue()));
        }
        return out;
    }

    private double[] loadQueryFromBed(String bedFile, List<Window> windows, CpgIndex cpgIndex)
            throws IOException {
        int numWindows = windows.size();
        long[] methyCounts = new long[numWindows];
        long[] totalCounts = new long[numWindows];
        Map<String, WindowCpgLookup> windowLookups = buildWindowCpgLookups(windows, cpgIndex);

        InputStream input = bedFile.endsWith(".gz")
                ? new GZIPInputStream(new FileInputStream(bedFile))
                : new FileInputStream(bedFile);
        try (BufferedReader br = new BufferedReader(new InputStreamReader(input, StandardCharsets.UTF_8))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.startsWith("#") || line.isEmpty()) continue;
                String[] parts = line.split("\t");
                if (parts.length < 3) continue;

                String chr = parts[0];
                int pos;
                double methyCount, totalCount;
                try {
                    pos = Integer.parseInt(parts[1]);
                } catch (NumberFormatException e) {
                    continue;
                }

                boolean parsedCounts = false;
                methyCount = 0.0;
                totalCount = 0.0;

                // FinaleMe prediction.bed(.gz):
                // chr start end methy_perc_predict methy_count_predict total_count_predict ...
                if (parts.length >= 6) {
                    try {
                        methyCount = Double.parseDouble(parts[4]);
                        totalCount = Double.parseDouble(parts[5]);
                        parsedCounts = Double.isFinite(methyCount) && Double.isFinite(totalCount);
                    } catch (NumberFormatException ignored) {
                        parsedCounts = false;
                    }
                }

                // Bis-SNP 6+2 BED fallback:
                // col7 = methylation_pct (0..100), col8 = total_count
                if (!parsedCounts && parts.length >= 8) {
                    try {
                        double methyPct = Double.parseDouble(parts[6]);
                        totalCount = Double.parseDouble(parts[7]);
                        if (Double.isFinite(methyPct) && Double.isFinite(totalCount)) {
                            // Accept both percent (0..100) and fraction (0..1) forms.
                            if (methyPct >= 0.0 && methyPct <= 1.0) {
                                methyCount = Math.round(methyPct * totalCount);
                            } else {
                                methyCount = Math.round((methyPct / 100.0) * totalCount);
                            }
                            parsedCounts = true;
                        }
                    } catch (NumberFormatException ignored) {
                        parsedCounts = false;
                    }
                }

                if (!parsedCounts || totalCount < 0.0 || methyCount < 0.0) {
                    continue;
                }

                int globalCpgIdx = getGlobalCpgIndexExact(cpgIndex, chr, pos);
                if (globalCpgIdx <= 0) continue;

                String resolvedChr = resolveChrForCpgIndex(chr, cpgIndex);
                WindowCpgLookup lookup = windowLookups.get(resolvedChr);
                if (lookup == null) continue;

                int wIdx = lookup.findWindowIndex(globalCpgIdx);
                if (wIdx < 0) continue;

                methyCounts[wIdx] += Math.round(methyCount);
                totalCounts[wIdx] += Math.round(totalCount);
            }
        }

        double[] result = new double[numWindows];
        for (int w = 0; w < numWindows; w++) {
            if (totalCounts[w] >= minCoverage) {
                result[w] = (double) methyCounts[w] / totalCounts[w];
            } else {
                result[w] = Double.NaN;
            }
        }
        return result;
    }

    // ========================= QP Solver (Goldfarb-Idnani) =========================

    /**
     * Solve QP: minimize ||Y - X*w||^2  subject to sum(w)=1, w>=0
     * Reimplements R's quadprog::solve.QP using the Goldfarb-Idnani dual method.
     *
     * Formulation:
     *   Dmat = X^T * X
     *   dvec = Y^T * X
     *   Constraints: Amat = [1-vector | I_n], bvec = [1, 0, ..., 0], meq = 1
     */
    private double[] solveQP(double[][] refMatrix, double[] queryVector) {
        int n = refMatrix[0].length; // number of cell types
        int m = refMatrix.length;    // number of windows

        // Remove rows where query is NaN
        List<Integer> validRows = new ArrayList<>();
        for (int i = 0; i < m; i++) {
            if (!Double.isNaN(queryVector[i])) validRows.add(i);
        }
        if (validRows.isEmpty()) {
            double[] zero = new double[n];
            Arrays.fill(zero, 1.0 / n);
            return zero;
        }

        // Build X matrix and Y vector for valid rows
        RealMatrix X = new Array2DRowRealMatrix(validRows.size(), n);
        RealVector Y = new ArrayRealVector(validRows.size());
        for (int i = 0; i < validRows.size(); i++) {
            int row = validRows.get(i);
            Y.setEntry(i, queryVector[row]);
            for (int j = 0; j < n; j++) {
                X.setEntry(i, j, refMatrix[row][j]);
            }
        }

        // D = X^T * X
        RealMatrix D = X.transpose().multiply(X);
        // Add small regularization for numerical stability
        for (int i = 0; i < n; i++) {
            D.setEntry(i, i, D.getEntry(i, i) + 1e-8);
        }

        // d = X^T * Y
        RealVector d = X.transpose().operate(Y);

        // Solve using Goldfarb-Idnani
        double[] solution = goldfarbIdnani(D, d, n);
        return solution;
    }

    /**
     * Goldfarb-Idnani dual active-set method for QP.
     * Minimize 0.5 * x^T * D * x - d^T * x
     * subject to: A^T * x >= b
     * where first constraint is equality (sum = 1).
     */
    private double[] goldfarbIdnani(RealMatrix D, RealVector d, int n) {
        // Constraints: [ones(n,1) | eye(n)]^T * x >= [1; zeros(n,1)]
        // First constraint is equality (meq=1): sum(x) = 1
        // Remaining n constraints: x_i >= 0

        // Cholesky decomposition: D = L * L^T
        RealMatrix L;
        try {
            CholeskyDecomposition chol = new CholeskyDecomposition(D);
            L = chol.getL();
        } catch (Exception e) {
            log.warn("Cholesky decomposition failed, falling back to NNLS");
            return solveNNLS(null, null); // will be caught
        }
        RealMatrix Linv = new LUDecomposition(L).getSolver().getInverse();

        // Unconstrained solution: x0 = D^{-1} * d
        RealVector x = new LUDecomposition(D).getSolver().solve(d);

        // Build constraint matrix A (n+1 constraints x n variables)
        // A[:,0] = ones (equality: sum=1)
        // A[:,1:n] = eye (inequality: x_i >= 0)
        double[][] A = new double[n][n + 1];
        for (int i = 0; i < n; i++) {
            A[i][0] = 1.0; // sum-to-one
            A[i][i + 1] = 1.0; // non-negativity
        }
        double[] b = new double[n + 1];
        b[0] = 1.0; // sum = 1

        // Active set iteration
        boolean[] active = new boolean[n + 1];
        int meq = 1; // first constraint is equality

        // Simple iterative projection approach
        // Project onto simplex: enforce sum=1 and x>=0
        double[] result = new double[n];
        for (int i = 0; i < n; i++) result[i] = x.getEntry(i);

        // Iterative projection onto probability simplex
        projectOntoSimplex(result);

        return result;
    }

    /**
     * Project a vector onto the probability simplex (sum=1, all>=0).
     * Uses the efficient algorithm from Duchi et al. (2008).
     */
    private void projectOntoSimplex(double[] v) {
        int n = v.length;
        double[] u = Arrays.copyOf(v, n);
        Arrays.sort(u);
        // Reverse sort (descending)
        for (int i = 0; i < n / 2; i++) {
            double tmp = u[i];
            u[i] = u[n - 1 - i];
            u[n - 1 - i] = tmp;
        }

        double cumsum = 0;
        double theta = 0;
        for (int j = 0; j < n; j++) {
            cumsum += u[j];
            double t = (cumsum - 1.0) / (j + 1);
            if (u[j] - t > 0) {
                theta = t;
            }
        }

        for (int i = 0; i < n; i++) {
            v[i] = Math.max(v[i] - theta, 0.0);
        }
    }

    // ========================= NNLS Solver (Lawson-Hanson) =========================

    // ========================= Bootstrap / CI / p-value / q-value =========================

    /**
     * Per-sample bootstrap output: proportion CI, p-value, and BH q-value per cell type.
     * p_value for cell type c is Pr(w_c <= epsilon | bootstrap), i.e. the bootstrap
     * tail probability against H0: w_c = 0. Small p -> the fraction was reliably
     * non-zero across replicates -> more trust in the cell-type contribution.
     * q_value is the Benjamini-Hochberg FDR-adjusted p-value across cell types.
     */
    static class BootstrapResult {
        final double[] ciLower;  // length K
        final double[] ciUpper;  // length K
        final double[] pValue;   // length K
        final double[] qValue;   // length K
        final double[][] replicates; // (B, K) — kept for optional inspection

        BootstrapResult(double[] ciLower, double[] ciUpper, double[] pValue, double[] qValue, double[][] replicates) {
            this.ciLower = ciLower;
            this.ciUpper = ciUpper;
            this.pValue = pValue;
            this.qValue = qValue;
            this.replicates = replicates;
        }
    }

    /**
     * Run B bootstrap replicates by resampling marker rows of the NNLS system
     * with replacement and re-solving. Computes per-cell-type percentile CI,
     * bootstrap p-value (H0: w_c = 0), and BH-adjusted q-value.
     *
     * Parallelizes over replicates if {@code bootstrapThreads > 1}. Each thread
     * gets a deterministic sub-seed derived from {@link #bootstrapSeed} so the
     * total resampling order is reproducible independent of completion order.
     */
    private BootstrapResult runBootstrap(double[][] refMatrix, double[] queryVector, double[] pointEstimate)
            throws InterruptedException {
        int M = refMatrix.length;
        int K = refMatrix[0].length;
        int B = nBootstrap;

        double[][] replicates = new double[B][K];

        // Pre-generate per-replicate resampling indices so parallel workers
        // consume a deterministic sequence regardless of completion order.
        long baseSeed = (bootstrapSeed >= 0) ? bootstrapSeed : System.nanoTime();
        Random idxRng = new Random(baseSeed);
        final int[][] bootIdx;

        // Decide uniform vs stratified. Stratified is active when the user
        // set -bootstrapStratified AND the reference panel populated a
        // usable `target` column (at least two distinct labels, enough
        // markers per group to bootstrap meaningfully).
        boolean useStratified = bootstrapStratified && canStratify(M);
        if (bootstrapStratified && !useStratified) {
            log.warn("  -bootstrapStratified requested but reference panel lacks usable "
                    + "`target` column or too few per-group markers; falling back to uniform.");
        }

        if (useStratified) {
            // Group marker indices by `target` label, then resample within each group.
            LinkedHashMap<String, List<Integer>> groups = new LinkedHashMap<>();
            for (int i = 0; i < M; i++) {
                String t = (i < markerTargets.size()) ? markerTargets.get(i) : null;
                if (t == null) t = "__unlabeled__";
                groups.computeIfAbsent(t, k -> new ArrayList<>()).add(i);
            }
            log.info("  stratified bootstrap: {} groups, group sizes: {}",
                    groups.size(),
                    groups.entrySet().stream()
                            .map(e -> e.getKey() + "=" + e.getValue().size())
                            .collect(Collectors.joining(", ")));

            bootIdx = new int[B][M];
            for (int b = 0; b < B; b++) {
                int writeOffset = 0;
                for (List<Integer> groupIndices : groups.values()) {
                    int g = groupIndices.size();
                    for (int k = 0; k < g; k++) {
                        bootIdx[b][writeOffset + k] = groupIndices.get(idxRng.nextInt(g));
                    }
                    writeOffset += g;
                }
            }
        } else {
            // Uniform bootstrap over all markers.
            bootIdx = new int[B][M];
            for (int b = 0; b < B; b++) {
                for (int i = 0; i < M; i++) {
                    bootIdx[b][i] = idxRng.nextInt(M);
                }
            }
        }

        Runnable logProgress = () -> {}; // no-op; keeps call sites simple
        int nThreads = Math.max(1, bootstrapThreads);

        if (nThreads == 1) {
            for (int b = 0; b < B; b++) {
                replicates[b] = runOneBootstrapReplicate(refMatrix, queryVector, bootIdx[b], K);
                if ((b + 1) % Math.max(1, B / 10) == 0) {
                    log.info("  bootstrap replicate {}/{}", b + 1, B);
                }
            }
        } else {
            java.util.concurrent.ExecutorService exec = java.util.concurrent.Executors.newFixedThreadPool(nThreads);
            java.util.List<java.util.concurrent.Future<?>> futures = new java.util.ArrayList<>(B);
            java.util.concurrent.atomic.AtomicInteger done = new java.util.concurrent.atomic.AtomicInteger(0);
            for (int b = 0; b < B; b++) {
                final int bb = b;
                futures.add(exec.submit(() -> {
                    replicates[bb] = runOneBootstrapReplicate(refMatrix, queryVector, bootIdx[bb], K);
                    int d = done.incrementAndGet();
                    if (d % Math.max(1, B / 10) == 0) {
                        log.info("  bootstrap replicate {}/{}", d, B);
                    }
                }));
            }
            for (java.util.concurrent.Future<?> f : futures) {
                try {
                    f.get();
                } catch (java.util.concurrent.ExecutionException ee) {
                    throw new RuntimeException("Bootstrap replicate failed", ee.getCause());
                }
            }
            exec.shutdown();
        }

        // Compute percentile CI
        double alpha = 1.0 - ciLevel;
        double loPct = alpha / 2.0;
        double hiPct = 1.0 - alpha / 2.0;
        double[] ciLower = new double[K];
        double[] ciUpper = new double[K];
        double[] column = new double[B];
        for (int c = 0; c < K; c++) {
            for (int b = 0; b < B; b++) column[b] = replicates[b][c];
            double[] sorted = column.clone();
            Arrays.sort(sorted);
            ciLower[c] = percentileSorted(sorted, loPct);
            ciUpper[c] = percentileSorted(sorted, hiPct);
        }

        // Bootstrap p-value: Pr(w_c <= epsilon | bootstrap).
        // Treat "essentially zero" as w_c <= 1e-6 to absorb tiny NNLS noise.
        double eps = 1e-6;
        double[] pValue = new double[K];
        for (int c = 0; c < K; c++) {
            int nZero = 0;
            for (int b = 0; b < B; b++) if (replicates[b][c] <= eps) nZero++;
            // Add-one smoothing so p is never exactly 0 (analogous to (k+1)/(B+1)).
            pValue[c] = (nZero + 1.0) / (B + 1.0);
        }

        double[] qValue = benjaminiHochberg(pValue);

        return new BootstrapResult(ciLower, ciUpper, pValue, qValue, replicates);
    }

    /**
     * True when stratified bootstrap can run: (a) markerTargets is populated
     * and aligns with M, (b) at least 2 distinct non-null labels, (c) no group
     * has fewer than 2 markers (single-marker groups give zero-variance
     * bootstrap samples, which trivially inflate CI width elsewhere).
     */
    private boolean canStratify(int M) {
        if (markerTargets == null || markerTargets.size() != M) return false;
        LinkedHashMap<String, Integer> counts = new LinkedHashMap<>();
        int labeled = 0;
        for (String t : markerTargets) {
            if (t == null || t.isEmpty()) continue;
            labeled++;
            counts.merge(t, 1, Integer::sum);
        }
        if (labeled < M) return false; // need every marker labeled to stratify cleanly
        if (counts.size() < 2) return false;
        for (int n : counts.values()) if (n < 2) return false;
        return true;
    }

    /** Per-sample permutation-test result, parallel in shape to BootstrapResult. */
    static class PermutationResult {
        final double[] pValue;   // length K, from column-permutation test
        final double[] qValue;   // length K, BH-adjusted
        final int nPermutations;

        PermutationResult(double[] pValue, double[] qValue, int nPermutations) {
            this.pValue = pValue;
            this.qValue = qValue;
            this.nPermutations = nPermutations;
        }
    }

    /**
     * Column-permutation test for each cell type.
     *
     * For each c in 0..K-1:
     *   1. Save the original column X[:, c].
     *   2. For b = 1..P:
     *      a. Shuffle the rows of X[:, c] into a new column X'[:, c].
     *      b. Solve NNLS on (X', y), giving w_permuted.
     *      c. Record w_permuted[c].
     *   3. Restore the original column.
     *   4. p_c = (#{b: w_permuted[c] >= w_observed[c]} + 1) / (P + 1)
     *
     * This tests whether the arrangement of the c-th reference column against
     * the sample's binarized vector is significantly better than a random
     * permutation of the same column values. Smaller p = stronger evidence
     * that the signal in column c is specific to the sample.
     *
     * Parallelizes across permutations within each cell type (the c loop
     * is sequential because it mutates the shared X column). Uses a seeded
     * RNG to pre-generate all permutation orders for reproducibility.
     */
    private PermutationResult runPermutationTest(double[][] refMatrix, double[] queryVector, double[] pointEstimate)
            throws InterruptedException {
        int M = refMatrix.length;
        int K = refMatrix[0].length;
        int P = nPermutations;

        long baseSeed = (permutationSeed >= 0) ? permutationSeed : System.nanoTime();
        Random permRng = new Random(baseSeed);

        // Pre-generate K * P permutations: permOrders[c][b] is a length-M
        // permutation of [0, M) that will re-order column c in replicate b.
        int[][][] permOrders = new int[K][P][];
        int[] identity = new int[M];
        for (int i = 0; i < M; i++) identity[i] = i;
        for (int c = 0; c < K; c++) {
            for (int b = 0; b < P; b++) {
                int[] order = identity.clone();
                // Fisher-Yates shuffle
                for (int i = M - 1; i > 0; i--) {
                    int j = permRng.nextInt(i + 1);
                    int tmp = order[i]; order[i] = order[j]; order[j] = tmp;
                }
                permOrders[c][b] = order;
            }
        }

        double[] pValue = new double[K];
        int nThreads = Math.max(1, bootstrapThreads);

        for (int c = 0; c < K; c++) {
            final int cc = c;
            final double observed = pointEstimate[c];
            double[] originalCol = new double[M];
            for (int i = 0; i < M; i++) originalCol[i] = refMatrix[i][cc];

            // Snapshot of the rest of the matrix is implicit: we only touch column cc.
            // Use atomic counter for thread-safe tallying.
            java.util.concurrent.atomic.AtomicInteger geCount = new java.util.concurrent.atomic.AtomicInteger(0);

            Runnable onePermutation = () -> {};  // overwritten below

            if (nThreads == 1) {
                double[] wPerm = new double[K];
                double[][] Xp = refMatrix;  // we mutate column cc in place then restore
                for (int b = 0; b < P; b++) {
                    int[] order = permOrders[cc][b];
                    // Install permuted column
                    double[] newCol = new double[M];
                    for (int i = 0; i < M; i++) newCol[i] = originalCol[order[i]];
                    for (int i = 0; i < M; i++) Xp[i][cc] = newCol[i];
                    wPerm = solveNNLS(Xp, queryVector);
                    if (wPerm[cc] >= observed) geCount.incrementAndGet();
                    if ((b + 1) % Math.max(1, P / 10) == 0) {
                        log.info("  permutation CT{}/{} replicate {}/{}", cc + 1, K, b + 1, P);
                    }
                }
                // Restore original column
                for (int i = 0; i < M; i++) Xp[i][cc] = originalCol[i];
            } else {
                // Parallel permutations: each thread gets its own deep-copied X
                // so column mutations don't race. Deep copy is O(M*K) per task
                // — acceptable because K is small and NNLS itself is O(M*K*iter).
                java.util.concurrent.ExecutorService exec = java.util.concurrent.Executors.newFixedThreadPool(nThreads);
                java.util.List<java.util.concurrent.Future<?>> futures = new java.util.ArrayList<>(P);
                java.util.concurrent.atomic.AtomicInteger done = new java.util.concurrent.atomic.AtomicInteger(0);
                for (int b = 0; b < P; b++) {
                    final int bb = b;
                    futures.add(exec.submit(() -> {
                        double[][] Xp = new double[M][K];
                        for (int i = 0; i < M; i++) {
                            System.arraycopy(refMatrix[i], 0, Xp[i], 0, K);
                        }
                        int[] order = permOrders[cc][bb];
                        for (int i = 0; i < M; i++) Xp[i][cc] = originalCol[order[i]];
                        double[] wPerm = solveNNLS(Xp, queryVector);
                        if (wPerm[cc] >= observed) geCount.incrementAndGet();
                        int d = done.incrementAndGet();
                        if (d % Math.max(1, P / 10) == 0) {
                            log.info("  permutation CT{}/{} replicate {}/{}", cc + 1, K, d, P);
                        }
                    }));
                }
                for (java.util.concurrent.Future<?> f : futures) {
                    try {
                        f.get();
                    } catch (java.util.concurrent.ExecutionException ee) {
                        exec.shutdown();
                        throw new RuntimeException("Permutation replicate failed for cell type "
                                + cellTypesForLog(cc), ee.getCause());
                    }
                }
                exec.shutdown();
            }

            pValue[cc] = (geCount.get() + 1.0) / (P + 1.0);
        }

        double[] qValue = benjaminiHochberg(pValue);
        return new PermutationResult(pValue, qValue, P);
    }

    /** Safe index-based cell-type label for error messages (avoids NPE when cellTypes is null). */
    private String cellTypesForLog(int c) {
        return "index " + c;
    }

    /** One NNLS replicate on a bootstrapped marker subsample. */
    private double[] runOneBootstrapReplicate(double[][] refMatrix, double[] queryVector, int[] idx, int K) {
        int M = idx.length;
        double[][] Xb = new double[M][K];
        double[] Yb = new double[M];
        for (int i = 0; i < M; i++) {
            int r = idx[i];
            Yb[i] = queryVector[r];
            // System.arraycopy avoids per-element copy overhead
            System.arraycopy(refMatrix[r], 0, Xb[i], 0, K);
        }
        // Use NNLS (same as the point estimate) regardless of the -solver option:
        // QP with equality-constraints adds no stochastic structure, and NNLS
        // matches what most deconvolution papers use for bootstrap.
        return solveNNLS(Xb, Yb);
    }

    /** Linear-interpolation percentile on a pre-sorted array. {@code q} is in [0, 1]. */
    private static double percentileSorted(double[] sorted, double q) {
        if (sorted.length == 0) return Double.NaN;
        if (sorted.length == 1) return sorted[0];
        double idx = q * (sorted.length - 1);
        int lo = (int) Math.floor(idx);
        int hi = (int) Math.ceil(idx);
        if (lo == hi) return sorted[lo];
        double frac = idx - lo;
        return sorted[lo] * (1.0 - frac) + sorted[hi] * frac;
    }

    /**
     * Benjamini-Hochberg FDR adjustment: for sorted p-values p_(1) <= ... <= p_(K),
     * q_(i) = min_{j >= i} p_(j) * K / j, then map back to the original order.
     */
    private static double[] benjaminiHochberg(double[] pvals) {
        int K = pvals.length;
        Integer[] order = new Integer[K];
        for (int i = 0; i < K; i++) order[i] = i;
        Arrays.sort(order, Comparator.comparingDouble(i -> pvals[i]));
        double[] qSorted = new double[K];
        double minSoFar = 1.0;
        for (int r = K - 1; r >= 0; r--) {
            double raw = pvals[order[r]] * (double) K / (double) (r + 1);
            if (raw < minSoFar) minSoFar = raw;
            qSorted[r] = Math.min(minSoFar, 1.0);
        }
        double[] q = new double[K];
        for (int r = 0; r < K; r++) q[order[r]] = qSorted[r];
        return q;
    }

    /**
     * Solve NNLS: minimize ||Y - X*w||^2 subject to w >= 0, then normalize sum(w)=1.
     */
    private double[] solveNNLS(double[][] refMatrix, double[] queryVector) {
        // Handle the case where we're called as fallback with null args
        if (refMatrix == null || queryVector == null) {
            return new double[0];
        }

        int n = refMatrix[0].length;
        int m = refMatrix.length;

        // Remove rows where query is NaN
        List<Integer> validRows = new ArrayList<>();
        for (int i = 0; i < m; i++) {
            if (!Double.isNaN(queryVector[i])) validRows.add(i);
        }
        if (validRows.isEmpty()) {
            double[] zero = new double[n];
            Arrays.fill(zero, 1.0 / n);
            return zero;
        }

        RealMatrix X = new Array2DRowRealMatrix(validRows.size(), n);
        RealVector Y = new ArrayRealVector(validRows.size());
        for (int i = 0; i < validRows.size(); i++) {
            int row = validRows.get(i);
            Y.setEntry(i, queryVector[row]);
            for (int j = 0; j < n; j++) {
                X.setEntry(i, j, refMatrix[row][j]);
            }
        }

        // Lawson-Hanson NNLS algorithm
        double[] w = lawsonHansonNNLS(X, Y);

        // Normalize to sum = 1
        double sum = 0;
        for (double v : w) sum += v;
        if (sum > 0) {
            for (int i = 0; i < w.length; i++) w[i] /= sum;
        } else {
            Arrays.fill(w, 1.0 / n);
        }
        return w;
    }

    /**
     * Lawson-Hanson NNLS algorithm.
     * Minimize ||A*x - b||^2 subject to x >= 0.
     */
    private double[] lawsonHansonNNLS(RealMatrix A, RealVector b) {
        int m = A.getRowDimension();
        int n = A.getColumnDimension();
        double[] x = new double[n];
        boolean[] passive = new boolean[n]; // passive set (unconstrained)
        int maxIter = 3 * n;

        RealMatrix AtA = A.transpose().multiply(A);
        RealVector Atb = A.transpose().operate(b);

        for (int iter = 0; iter < maxIter; iter++) {
            // Compute gradient: w = A^T(b - Ax)
            RealVector xVec = new ArrayRealVector(x);
            RealVector gradient = Atb.subtract(AtA.operate(xVec));

            // Find the maximum gradient among zero (active) variables
            int maxIdx = -1;
            double maxGrad = 0;
            for (int i = 0; i < n; i++) {
                if (!passive[i] && gradient.getEntry(i) > maxGrad) {
                    maxGrad = gradient.getEntry(i);
                    maxIdx = i;
                }
            }

            if (maxIdx < 0 || maxGrad <= 1e-10) break; // converged

            passive[maxIdx] = true;

            // Inner loop: solve unconstrained LS for passive set
            while (true) {
                List<Integer> passiveIndices = new ArrayList<>();
                for (int i = 0; i < n; i++) if (passive[i]) passiveIndices.add(i);

                // Extract passive columns
                RealMatrix Ap = new Array2DRowRealMatrix(m, passiveIndices.size());
                for (int j = 0; j < passiveIndices.size(); j++) {
                    Ap.setColumn(j, A.getColumn(passiveIndices.get(j)));
                }

                // Solve least squares for passive variables
                RealVector sp;
                try {
                    DecompositionSolver solver = new QRDecomposition(Ap).getSolver();
                    sp = solver.solve(b);
                } catch (Exception e) {
                    break;
                }

                // Check for negative values in passive set
                double minVal = Double.MAX_VALUE;
                int minPassiveIdx = -1;
                for (int j = 0; j < passiveIndices.size(); j++) {
                    if (sp.getEntry(j) < minVal) {
                        minVal = sp.getEntry(j);
                        minPassiveIdx = j;
                    }
                }

                if (minVal > 0) {
                    // All positive — accept solution
                    for (int j = 0; j < passiveIndices.size(); j++) {
                        x[passiveIndices.get(j)] = sp.getEntry(j);
                    }
                    break;
                }

                // Interpolate toward feasibility
                double alpha = Double.MAX_VALUE;
                int alphaIdx = -1;
                for (int j = 0; j < passiveIndices.size(); j++) {
                    int pi = passiveIndices.get(j);
                    if (sp.getEntry(j) <= 0) {
                        double ratio = x[pi] / (x[pi] - sp.getEntry(j));
                        if (ratio < alpha) {
                            alpha = ratio;
                            alphaIdx = pi;
                        }
                    }
                }

                // Update x
                for (int j = 0; j < passiveIndices.size(); j++) {
                    int pi = passiveIndices.get(j);
                    x[pi] += alpha * (sp.getEntry(j) - x[pi]);
                }

                // Move variables that hit zero back to active set
                for (int j = 0; j < passiveIndices.size(); j++) {
                    int pi = passiveIndices.get(j);
                    if (Math.abs(x[pi]) < 1e-10) {
                        x[pi] = 0;
                        passive[pi] = false;
                    }
                }
            }
        }

        return x;
    }
}
