"""Output writers for per-sample TSVs, cohort summaries, and reports."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

from finaleme_too.core.deconvolution import DeconvolutionResult


def _format_proportion(x: float) -> float:
    return float(round(x, 4))


def _write_sample_transposed(
    df_samples: pd.DataFrame,
    path: str | Path,
) -> None:
    """Write a sample-keyed dataframe as metric rows × sample columns.

    Input shape is expected to be one row per sample with a ``sample_id``
    column. Output shape is transposed with:
      - first column: ``metric``
      - one subsequent column per sample id.
    """
    if df_samples.empty:
        pd.DataFrame(columns=["metric"]).to_csv(path, sep="\t", index=False)
        return
    if "sample_id" not in df_samples.columns:
        df_samples.to_csv(path, sep="\t", index=False, float_format="%.4f")
        return

    sample_order = [str(s) for s in df_samples["sample_id"].tolist()]
    tsv = df_samples.set_index("sample_id").T
    # Keep the original sample order from the rows.
    tsv = tsv.loc[:, sample_order]
    tsv.insert(0, "metric", tsv.index.astype(str))
    tsv = tsv.reset_index(drop=True)
    tsv.to_csv(path, sep="\t", index=False, float_format="%.4f")


# Header comment prepended to every per-sample .too.tsv file.
# ``pandas.read_csv(..., sep='\t', comment='#')`` reads these files without
# any extra arguments.
_TOO_TSV_HEADER_COMMENT = """\
# finaleme-too per-sample cell-type proportions
# Generated by: finaleme_too
# Column semantics:
#   cell_type        — reference cell type label; "Unknown" is the unmodeled residual
#   proportion       — point-estimate proportion (0..1), sums to ~1 including Unknown
#   ci_lower/ci_upper— bootstrap (or posterior) credible interval for the proportion
#   p_detection      — fraction of bootstrap replicates where this cell type was above
#                      the noise floor (NOT a traditional p-value despite the name)
#                        HIGH = reliably detected; > 0.95 → reliably above noise
#                        LOW  = unstable; < 0.10 → likely noise
#   likelihood_score — weighted per-marker log-likelihood gain (nats/marker)
#                      vs the same ablated null model (higher is better)
#   p_likelihood     — likelihood-ratio p-value vs the same ablated null
#                      (smaller is better; <0.05 usually indicates real gain)
#   reliability      — HIGH / MODERATE / LOW / UNRELIABLE combining p_detection,
#                      likelihood_score, and p_likelihood
#   n_markers        — number of markers contributing to this cell type's estimate
#   mean_dispersion  — mean beta-binomial dispersion phi over the top discriminative
#                      markers for this cell type (larger = tighter, less noisy)
#
# TL;DR: HIGH = GOOD; reliability tracks p_detection + fit gains.
"""


def write_per_sample_too(result: DeconvolutionResult, path: str | Path) -> None:
    """Write a per-sample TSV with one row per cell type (incl. unknown).

    Output columns (architecture §10.1):
        cell_type proportion ci_lower ci_upper p_detection
        likelihood_score p_likelihood reliability n_markers mean_dispersion

    The file begins with a ``#``-prefixed header comment documenting the
    high-confusability column semantics (see ``_TOO_TSV_HEADER_COMMENT``).
    Use ``pd.read_csv(path, sep='\\t', comment='#')`` to read these files.
    """
    rows = []
    cell_type_labels = list(result.cell_types) + ["Unknown"]
    K = len(result.cell_types)
    for i, ct in enumerate(cell_type_labels):
        lik = (
            float(result.likelihood_score[i])
            if result.likelihood_score is not None and i < len(result.likelihood_score)
            else float("nan")
        )
        plik = (
            float(result.p_likelihood[i])
            if result.p_likelihood is not None and i < len(result.p_likelihood)
            else float("nan")
        )
        n_mark = int(result.n_markers[i]) if i < K and result.n_markers is not None else 0
        mean_disp = (
            float(result.mean_dispersion[i])
            if i < K and result.mean_dispersion is not None
            else float("nan")
        )
        rows.append(
            {
                "cell_type": ct,
                "proportion": _format_proportion(result.proportions[i]),
                "ci_lower": _format_proportion(result.ci_lower[i]),
                "ci_upper": _format_proportion(result.ci_upper[i]),
                "p_detection": float(result.p_detection[i]),
                "likelihood_score": lik,
                "p_likelihood": plik,
                "reliability": str(result.reliability[i]),
                "n_markers": n_mark,
                "mean_dispersion": mean_disp,
            }
        )
    df = pd.DataFrame(rows)
    # Write the header comment, then append the DataFrame rows. Using the
    # two-phase write keeps the body identical to the previous version, so
    # any downstream consumer that already passes ``comment='#'`` to
    # read_csv gets the same data columns.
    out_path = Path(path)
    out_path.write_text(_TOO_TSV_HEADER_COMMENT)
    with out_path.open("a") as fh:
        df.to_csv(fh, sep="\t", index=False, float_format="%.4f")


def write_cohort_proportions(
    results: list[DeconvolutionResult],
    sample_groups: dict[str, str | None],
    path: str | Path,
) -> None:
    """Write cohort_proportions.tsv with one column per sample.

    Internal table is built as one row per sample, then transposed to
    metrics-as-rows so each sample is a dedicated output column.
    """
    if not results:
        pd.DataFrame(columns=["metric"]).to_csv(path, sep="\t", index=False)
        return

    base = results[0]
    cell_type_labels = list(base.cell_types) + ["Unknown"]
    K = len(base.cell_types)

    columns = [
        "sample_id",
        "group",
        "coverage_tier",
        "mean_coverage",
        "n_markers_used",
        "pct_imputed",
    ]
    for ct in cell_type_labels:
        columns.append(ct)
        columns.append(f"{ct}_ci_lo")
        columns.append(f"{ct}_ci_hi")
        columns.append(f"{ct}_p_detection")
        columns.append(f"{ct}_likelihood_score")
        columns.append(f"{ct}_p_likelihood")
        columns.append(f"{ct}_reliability")
    columns.extend(
        [
            "binarization_flag",
            "hemolysis",
            "qc_flags",
            "overall_qc",
        ]
    )

    rows = []
    for r in results:
        row = {
            "sample_id": r.sample_id,
            "group": sample_groups.get(r.sample_id),
            "coverage_tier": r.coverage_tier.value if hasattr(r.coverage_tier, "value") else str(r.coverage_tier),
            "mean_coverage": float(r.mean_coverage),
            "n_markers_used": int(r.n_markers_used),
            "pct_imputed": _format_proportion(r.pct_imputed),
        }
        for i, ct in enumerate(cell_type_labels):
            row[ct] = _format_proportion(r.proportions[i])
            row[f"{ct}_ci_lo"] = _format_proportion(r.ci_lower[i])
            row[f"{ct}_ci_hi"] = _format_proportion(r.ci_upper[i])
            row[f"{ct}_p_detection"] = float(r.p_detection[i])
            if r.likelihood_score is not None and i < len(r.likelihood_score):
                row[f"{ct}_likelihood_score"] = float(r.likelihood_score[i])
            else:
                row[f"{ct}_likelihood_score"] = float("nan")
            if r.p_likelihood is not None and i < len(r.p_likelihood):
                row[f"{ct}_p_likelihood"] = float(r.p_likelihood[i])
            else:
                row[f"{ct}_p_likelihood"] = float("nan")
            row[f"{ct}_reliability"] = str(r.reliability[i])
        row["binarization_flag"] = r.binarization_flag or "NA"
        row["hemolysis"] = (
            "TRUE" if r.hemolysis_flag is True
            else ("FALSE" if r.hemolysis_flag is False else "NA")
        )
        row["qc_flags"] = ",".join(r.qc_flags) if r.qc_flags else "NONE"
        row["overall_qc"] = r.overall_qc
        rows.append(row)

    _write_sample_transposed(pd.DataFrame(rows, columns=columns), path)


def write_qc_summary(
    results: list[DeconvolutionResult],
    sample_groups: dict[str, str | None],
    path: str | Path,
) -> None:
    """Write a transposed QC summary (metrics rows, samples columns).

    Columns:
        sample_id group coverage_tier mean_coverage n_markers_used
        pct_imputed wbc_fraction unknown_fraction binarization_flag
        hemolysis qc_flags overall_qc

    The ``binarization_flag`` column was renamed from ``calibration_flag``
    in v3 to reflect the FinaleMe path's switch from continuous calibration
    to context-dependent binarization. Values (PASS / WARN / FAIL) and
    semantics are unchanged.
    """
    rows = []
    for r in results:
        unknown = float(r.proportions[-1])
        # WBC fraction = sum of proportions for cell types whose name starts
        # with "Blood" (matches the qc.py heuristic)
        blood_idx = [
            i for i, ct in enumerate(r.cell_types) if ct.lower().startswith("blood")
        ]
        wbc = float(np.sum(r.proportions[blood_idx])) if blood_idx else float("nan")
        rows.append(
            {
                "sample_id": r.sample_id,
                "group": sample_groups.get(r.sample_id),
                "coverage_tier": r.coverage_tier.value if hasattr(r.coverage_tier, "value") else str(r.coverage_tier),
                "mean_coverage": float(r.mean_coverage),
                "n_markers_used": int(r.n_markers_used),
                "pct_imputed": _format_proportion(r.pct_imputed),
                "wbc_fraction": _format_proportion(wbc) if not np.isnan(wbc) else float("nan"),
                "unknown_fraction": _format_proportion(unknown),
                "binarization_flag": r.binarization_flag or "NA",
                "hemolysis": (
                    "TRUE" if r.hemolysis_flag is True
                    else ("FALSE" if r.hemolysis_flag is False else "NA")
                ),
                "qc_flags": ",".join(r.qc_flags) if r.qc_flags else "NONE",
                "overall_qc": r.overall_qc,
            }
        )
    _write_sample_transposed(pd.DataFrame(rows), path)


def write_binarization_debug(
    results: list[DeconvolutionResult],
    sample_groups: dict[str, str | None],
    path: str | Path,
) -> None:
    """Write a per-sample FinaleMe binarization debug report.

    This report is intentionally compact and focused on answering:
    "why did this sample end up with n_markers_used == 0 / unknown == 1?"

    Rows are emitted only for samples where ``result.binarization_debug`` is
    populated (i.e. FinaleMe + binarization path). Non-FinaleMe samples are
    skipped.
    """
    rows = []
    for r in results:
        dbg = r.binarization_debug
        if not isinstance(dbg, dict) or not dbg:
            continue
        row = {
            "sample_id": r.sample_id,
            "group": sample_groups.get(r.sample_id),
        }
        row.update(dbg)
        rows.append(row)
    if not rows:
        return
    pd.DataFrame(rows).to_csv(path, sep="\t", index=False, float_format="%.6g")


def write_group_comparison(
    test_results: list,  # list[TestResult]
    path: str | Path,
) -> None:
    """Write group_comparison.tsv (architecture §10.3)."""
    rows = []
    for r in test_results:
        rows.append(
            {
                "test_type": r.test_type,
                "contrast": r.contrast,
                "cell_type": r.cell_type,
                "mean_A": r.mean_a,
                "mean_B": r.mean_b,
                "effect_size": r.effect_size,
                "se": r.se,
                "statistic": r.statistic,
                "p_value": r.p_value,
                "adjusted_p": r.adjusted_p_value,
                "significant": r.significant,
            }
        )
    pd.DataFrame(rows).to_csv(path, sep="\t", index=False, float_format="%.4g")


def write_residual_analysis(
    results: list[DeconvolutionResult],
    sample_groups: dict[str, str | None],
    path: str | Path,
    nmf_summary: dict | None = None,
) -> None:
    """Write residual_analysis.tsv (metrics rows, samples columns).

    Columns:
        sample_id group coverage_tier unexplained_fraction mean_residual
        residual_sd nmf_top_component_loading qc_flag
    """
    rows = []
    loading_by_sample: dict[str, float] = {}
    if nmf_summary is not None:
        loadings = nmf_summary.get("loadings")
        sample_order = nmf_summary.get("sample_order")
        if loadings is not None and sample_order is not None and len(sample_order) > 0:
            # Use the per-sample max loading as a "top component" signature
            loadings_arr = np.asarray(loadings, dtype=np.float64)
            if loadings_arr.ndim == 2 and loadings_arr.shape[1] > 0:
                for sid, row in zip(sample_order, loadings_arr):
                    loading_by_sample[sid] = float(np.max(row))

    for r in results:
        if r.residuals is None or r.residuals.size == 0:
            unexplained = float(r.proportions[-1])
            mean_res = float("nan")
            sd_res = float("nan")
        else:
            finite = r.residuals[np.isfinite(r.residuals)]
            unexplained = float(r.proportions[-1])
            mean_res = float(np.mean(finite)) if finite.size else float("nan")
            sd_res = float(np.std(finite)) if finite.size else float("nan")
        rows.append(
            {
                "sample_id": r.sample_id,
                "group": sample_groups.get(r.sample_id),
                "coverage_tier": r.coverage_tier.value
                if hasattr(r.coverage_tier, "value")
                else str(r.coverage_tier),
                "unexplained_fraction": _format_proportion(unexplained),
                "mean_residual": mean_res,
                "residual_sd": sd_res,
                "nmf_top_component_loading": loading_by_sample.get(
                    r.sample_id, float("nan")
                ),
                "qc_flag": r.overall_qc,
            }
        )
    _write_sample_transposed(pd.DataFrame(rows), path)


def write_calibration_report(report: dict, path: str | Path) -> None:
    Path(path).write_text(json.dumps(report, indent=2, default=_json_default))


def _json_default(obj):
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, (np.floating, np.integer)):
        return obj.item()
    raise TypeError(f"Type {type(obj)} not JSON serializable")


__all__ = [
    "write_binarization_debug",
    "write_calibration_report",
    "write_cohort_proportions",
    "write_group_comparison",
    "write_per_sample_too",
    "write_qc_summary",
    "write_residual_analysis",
]
