/* jahmm package - v0.6.1 */

/*
  *  Copyright (c) 2004-2006, Jean-Marc Francois.
 *
 *  This file is part of Jahmm.
 *  Jahmm is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  Jahmm is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Jahmm; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 */

package org.cchmc.epifluidlab.finaleme.hmm;

import java.util.ArrayList;

import be.ac.ulg.montefiore.run.jahmm.OpdfFactory;


/**
 * This class can build <code>OpdfMultiGaussian</code> observation probability 
 * functions.
 */
public class OpdfMultiMixtureGaussianFactory 
implements OpdfFactory<OpdfMultiMixtureGaussian>
{	
	private int dimension;
	private ArrayList<Integer> mixNumberInFeature;
	public double[] mean;
	public double[] variance;

	
	/**
	 * Generates a new multivariate gaussian observation probability 
	 * distribution function.
	 * 
	 * @param dimension The dimension of the vectors generated by this
	 *                  object.
	 */
	
	public OpdfMultiMixtureGaussianFactory(int dimension, ArrayList<Integer> mixNumberInFeature)
	{
		this.dimension = dimension;
		this.mixNumberInFeature = mixNumberInFeature;
	}
	

	public OpdfMultiMixtureGaussianFactory(int dimension, ArrayList<Integer> mixNumberInFeature, double[] mean, double[] variance)
	{
		this.dimension = dimension;
		this.mixNumberInFeature = mixNumberInFeature;
		this.mean = mean;
		this.variance = variance;

	}

	
	public OpdfMultiMixtureGaussian factor()
	{
		if(mean != null){
			return new OpdfMultiMixtureGaussian(dimension, mixNumberInFeature, mean, variance);
		}else{
			return new OpdfMultiMixtureGaussian(dimension, mixNumberInFeature);
		}
		
	}
	
	
}
